name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1

      - name: Nuget restore       
        run: nuget restore

      - name: Sudo
        run:  sudo apt-get dotnet-dev-1.0.0-preview3-00456

      - name: Build app for release
        run:  dotnet build --configuration Release
        
      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1
        with:
          install: sqlengine, sqlclient, sqlpackage

      - name: Run Unit Tests
        run: dotnet test ./test/Globalmantics.UnitTests/Globalmantics.UnitTests.csproj --logger "trx;LogFileName=test-result.trx"

      - name: Run Integration Tests
        run: dotnet test ./test/Globalmantics.IntegrationTests/Globalmantics.IntegrationTests.csproj --logger "trx;LogFileName=test-result.trx"
      
      - name: Unit Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: '.\test\Globalmantics.UnitTests\TestResults\*.trx'

      - name: Integration Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: integration-test-results
          path: '.\test\Globalmantics.IntegrationTests\TestResults\*.trx'